stages:
  - build

variables:
  IMAGE_NAME: asterisk-custom
  TAG_NAME: latest

build_image:
  stage: build
  image: docker:20.10
  services:
    - docker:20.10-dind
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY"
  script:
    - docker build -t $CI_REGISTRY_IMAGE/$IMAGE_NAME:$TAG_NAME .
    - docker push $CI_REGISTRY_IMAGE/$IMAGE_NAME:$TAG_NAME
  only:
    - main
